Fixed issue of header missing in susie combined cred file in rare
FINNGEN/finemapping-pipeline pull request #30
Opened 2020-10-22 21:07 UTC by Fedja

occasions when susie returns empty result in a region and it happens to
be the first one in combin stage.

Added wdl to post-hoc filter and summarize full finemap run

Fixed duplicate cs column in filter and summarize

2020-10-25 09:21 UTC, mkanai requested changes
Thanks Mitja! It looks great except a single line which seems some typo to me.

2020-10-25 09:21 UTC, mkanai commented on wdl/finemap_sub.wdl
> +        FNR == 1 { gsub(/[ \t]+$/, "", $0); if(header_printed==0 && $0!=""){ print "trait", "region", $0header_printed=1; } }
You have unnecessary line here.

2020-10-26 21:42 UTC, Fedja commented on wdl/finemap_sub.wdl
> +        FNR == 1 { gsub(/[ \t]+$/, "", $0); if(header_printed==0 && $0!=""){ print "trait", "region", $0header_printed=1; } }
agh... removed

2020-10-26 21:45 UTC, mkanai commented on wdl/finemap_sub.wdl
> +        FNR == 1 { gsub(/[ \t]+$/, "", $0); if(header_printed==0 && $0!=""){ print "trait", "region", $0header_printed=1; } }
thanks!

2020-10-26 21:45 UTC, mkanai approved these changes
Looks great now!

2020-10-26 21:46 UTC, merged